name: pymol-int

channels:
  - conda-forge
  - defaults
  - schrodinger

for windows uncomment this
dependencies:
  - python=3.11
  - pymol=2.5.3

# #For linux uncomment this
# dependencies:
#   - python=3.11
#   - pymol=2.5.3